/* 
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct BalanceApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> BalanceApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> BalanceApiClient<C> {
        BalanceApiClient {
            configuration: configuration,
        }
    }
}

pub trait BalanceApi {
    fn balance(&self, ) -> Box<Future<Item = ::models::Balance, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>BalanceApi for BalanceApiClient<C> {
    fn balance(&self, ) -> Box<Future<Item = ::models::Balance, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/balance.php".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: false,
                in_query: true,
                param_name: "key".to_owned(),
            }))
            .execute(self.configuration.borrow())
    }

}
