/*
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct BalanceApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> BalanceApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> BalanceApiClient<C> {
        BalanceApiClient {
            configuration,
        }
    }
}

pub trait BalanceApi {
    fn balance(&self, ) -> Box<dyn Future<Item = crate::models::Balance, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>BalanceApi for BalanceApiClient<C> {
    fn balance(&self, ) -> Box<dyn Future<Item = crate::models::Balance, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/balance.php".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: false,
                in_query: true,
                param_name: "key".to_owned(),
            }))
        ;

        req.execute(self.configuration.borrow())
    }

}
