/*
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct SearchApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> SearchApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> SearchApiClient<C> {
        SearchApiClient {
            configuration,
        }
    }
}

pub trait SearchApi {
    fn search(&self, q: &str, format: &str, normalizecity: i32, addressdetails: Option<i32>, viewbox: Option<&str>, bounded: Option<i32>, limit: Option<i32>, accept_language: Option<&str>, countrycodes: Option<&str>, namedetails: Option<i32>, dedupe: Option<i32>, extratags: Option<i32>, statecode: Option<i32>, matchquality: Option<i32>, postaladdress: Option<i32>) -> Box<dyn Future<Item = Vec<crate::models::Location>, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>SearchApi for SearchApiClient<C> {
    fn search(&self, q: &str, format: &str, normalizecity: i32, addressdetails: Option<i32>, viewbox: Option<&str>, bounded: Option<i32>, limit: Option<i32>, accept_language: Option<&str>, countrycodes: Option<&str>, namedetails: Option<i32>, dedupe: Option<i32>, extratags: Option<i32>, statecode: Option<i32>, matchquality: Option<i32>, postaladdress: Option<i32>) -> Box<dyn Future<Item = Vec<crate::models::Location>, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/search.php".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: false,
                in_query: true,
                param_name: "key".to_owned(),
            }))
        ;
        req = req.with_query_param("q".to_string(), q.to_string());
        req = req.with_query_param("format".to_string(), format.to_string());
        req = req.with_query_param("normalizecity".to_string(), normalizecity.to_string());
        if let Some(ref s) = addressdetails {
            req = req.with_query_param("addressdetails".to_string(), s.to_string());
        }
        if let Some(ref s) = viewbox {
            req = req.with_query_param("viewbox".to_string(), s.to_string());
        }
        if let Some(ref s) = bounded {
            req = req.with_query_param("bounded".to_string(), s.to_string());
        }
        if let Some(ref s) = limit {
            req = req.with_query_param("limit".to_string(), s.to_string());
        }
        if let Some(ref s) = accept_language {
            req = req.with_query_param("accept-language".to_string(), s.to_string());
        }
        if let Some(ref s) = countrycodes {
            req = req.with_query_param("countrycodes".to_string(), s.to_string());
        }
        if let Some(ref s) = namedetails {
            req = req.with_query_param("namedetails".to_string(), s.to_string());
        }
        if let Some(ref s) = dedupe {
            req = req.with_query_param("dedupe".to_string(), s.to_string());
        }
        if let Some(ref s) = extratags {
            req = req.with_query_param("extratags".to_string(), s.to_string());
        }
        if let Some(ref s) = statecode {
            req = req.with_query_param("statecode".to_string(), s.to_string());
        }
        if let Some(ref s) = matchquality {
            req = req.with_query_param("matchquality".to_string(), s.to_string());
        }
        if let Some(ref s) = postaladdress {
            req = req.with_query_param("postaladdress".to_string(), s.to_string());
        }

        req.execute(self.configuration.borrow())
    }

}
