/* 
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Daybalance {
  #[serde(rename = "day")]
  day: Option<i32>,
  #[serde(rename = "bonus")]
  bonus: Option<i32>
}

impl Daybalance {
  pub fn new() -> Daybalance {
    Daybalance {
      day: None,
      bonus: None
    }
  }

  pub fn set_day(&mut self, day: i32) {
    self.day = Some(day);
  }

  pub fn with_day(mut self, day: i32) -> Daybalance {
    self.day = Some(day);
    self
  }

  pub fn day(&self) -> Option<&i32> {
    self.day.as_ref()
  }

  pub fn reset_day(&mut self) {
    self.day = None;
  }

  pub fn set_bonus(&mut self, bonus: i32) {
    self.bonus = Some(bonus);
  }

  pub fn with_bonus(mut self, bonus: i32) -> Daybalance {
    self.bonus = Some(bonus);
    self
  }

  pub fn bonus(&self) -> Option<&i32> {
    self.bonus.as_ref()
  }

  pub fn reset_bonus(&mut self) {
    self.bonus = None;
  }

}



