/*
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectionsDirectionsRoutes {
    #[serde(rename = "legs", skip_serializing_if = "Option::is_none")]
    pub legs: Option<Vec<serde_json::Value>>,
    #[serde(rename = "weight_name", skip_serializing_if = "Option::is_none")]
    pub weight_name: Option<String>,
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<String>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f32>,
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f32>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f32>,
}

impl DirectionsDirectionsRoutes {
    pub fn new() -> DirectionsDirectionsRoutes {
        DirectionsDirectionsRoutes {
            legs: None,
            weight_name: None,
            geometry: None,
            weight: None,
            distance: None,
            duration: None,
        }
    }
}


