/*
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectionsMatching {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "tracepoints", skip_serializing_if = "Option::is_none")]
    pub tracepoints: Option<Vec<serde_json::Value>>,
    #[serde(rename = "matchings", skip_serializing_if = "Option::is_none")]
    pub matchings: Option<Vec<serde_json::Value>>,
}

impl DirectionsMatching {
    pub fn new() -> DirectionsMatching {
        DirectionsMatching {
            code: None,
            tracepoints: None,
            matchings: None,
        }
    }
}


