/*
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Matchquality {
    #[serde(rename = "matchcode", skip_serializing_if = "Option::is_none")]
    pub matchcode: Option<String>,
    #[serde(rename = "matchtype", skip_serializing_if = "Option::is_none")]
    pub matchtype: Option<String>,
    #[serde(rename = "matchlevel", skip_serializing_if = "Option::is_none")]
    pub matchlevel: Option<String>,
}

impl Matchquality {
    pub fn new() -> Matchquality {
        Matchquality {
            matchcode: None,
            matchtype: None,
            matchlevel: None,
        }
    }
}


